### ISSUE TITLE
Nefunkční routy pro nette-sandbox (PHP 7.1.3 - Nette 2.4 - Apache 2.4.10)

### ISSUE THREAD

**Issue by BigOHenry** [contributte/api-router#12]
Zdravím,
zkouším rozchodit příklady z tvého webu pro ApiRouter a ApiDocu na nette-sandboxu, ale stále dostávám chybu 
`Nette\Application\BadRequestException #404
No route for HTTP request.`

Příklad jsem umístil na svůj [GitHub](https://github.com/BigOHenry/sandbox )

Vůbec nevím proč to nejde. Díky moc

**Comment by mabar** [comment]
Obávám se, že je to nereprodukovatelné. Naklonoval jsem si repositář a routy tam mám.
Zkusil jsi smazat cache?

**Comment by pitr82** [comment]
@BigOHenry taky mi ten tvůj projekt nejede.
Ahoj @paveljanda , nemáš funkční SandBox ?

**Comment by paveljanda** [comment]
https://github.com/ublaboo/api-router-project :) :)

**Comment by pitr82** [comment]
@paveljanda  Ahoj, 
zkoušel jsem, projekt.
Konkrétněna URL :
curl -X POST localhost/api-router-project/www/api/login

všiml jsem si, že v "cache/ApiRouter.Annotations/"
mám same blbosti
obash souboru:
0
a:0:{}

nebo

0
i:1499078098;

oproti Doctrine.anotation, kde jsou srozumitelné texty... 

Kde dělám chybu ?

**Comment by mabar** [comment]
Projdi si všechny soubory, já nějaká data našel až v tom posledním, zbytek to samé, co ty. Těžko říct, proč jsou tam ty prázdné.

**Comment by pitr82** [comment]
@mabar, ano v tom posledním jsou same čísla. 
curl -X POST localhost/api-router-project/www/api/login
tohle ti vypíše date ? Já mám pořád BadRequestException: No route for HTTP request. #404

**Comment by paveljanda** [comment]
@pitr82 Zkus si přidat vhosta. To bude ten problém.

**Comment by paveljanda** [comment]
1, Měla by se někde pořešit basePath
2, Prosím piště issues anglicky

**Comment by pitr82** [comment]
@paveljanda vhost works, 
Can you help me with basePath on localhost?

**Comment by paveljanda** [comment]
@pitr82 I have to add some functionality do api-router to support basePath :)
