### ISSUE TITLE
Routy nematchuji, je-li script zanoreny v ceste

### ISSUE THREAD

**Issue by icaine** [contributte/api-router#15]
Zdravim,

https://github.com/ublaboo/api-router/blob/989be1ba76085c5cc943181e8f5c296cd9182359/src/ApiRoute.php#L273 by melo byt nahrazeno za `getPathInto()`, pripadne i jinde, kde se na toto nemyslelo.

Je-li cela cesta napr `http://localhost/cesta/ke/skriptu/api/v1/user/` a definice routy `api/v1/user/`, pak se generuje pattern pro regexp `/^\/api\/v1\/user\/$/`, ktery kvuli `^` nemuze nikdy matchnout.

**Comment by f3l1x** [comment]
Solved via https://github.com/contributte/api-router/commit/ba5d23cd
