### ISSUE TITLE
Nette/Object deprecated - use Nette/SmartObject 

### ISSUE THREAD

**Issue by BigOHenry** [contributte/api-router#17]
Hello, please add support for new nette/utils 2.5.x.

**Comment by paveljanda** [comment]
What version do you use? There is no more Nette\Object usage. :)

**Comment by BigOHenry** [comment]
Ahhh, sorry my bad. I didnt notice you have 2.x version already :) 

I updated the api-docu and api-router to 2.x, but i have this problem:
**`Argument 1 passed to Ublaboo\ApiRouter\ApiRouteSpec::setDescription() must be of the type string, null given, called in /var/www/sep/vendor/ublaboo/api-router/src/DI/ApiRouterExtension.php on line 128`**

Do you know where could be a problem? Thank you very much

**Comment by paveljanda** [comment]
@BigOHenry Fixed in `2.0.3`

**Comment by BigOHenry** [comment]
Thank you, working now.
