### ISSUE TITLE
ApiRoute not matching

### ISSUE THREAD

**Issue by maxty45** [contributte/api-router#22]
I'm still quite a beginner in web apps, but I needed to run Nette with REST API. I tried Api-router, but have the following issue: Route in router factory doesn't match anything...

**My config.neon:**

application:
	errorPresenter: Error
	mapping:
		*: App\*Module\Presenters\*Presenter

security:
    debugger: true

session:
    expiration: 14 days
    debugger: true

services:
	- App\Model\UserManager(@nette.database.users.context)
	- App\Forms\FormFactory
	- App\Forms\SignInFormFactory
	- App\Forms\SignUpFormFactory
	router: App\RouterFactory::createRouter

extensions:
	apiRouter: Ublaboo\ApiRouter\DI\ApiRouterExtension

**My router:**

public static function createRouter()
	{
		$router = new RouteList;
                
                $router[] = new RouteList('Api');
                $router[] = new ApiRoute('/rest', 'Rest');   //doesn't work
                
                //$router[] = new Route('<presenter>/<action>/[<id>]', "Rest:read"); //this "workaround" works
                
                $router[] = new Route('index.php','Front:Default:default', Route::ONE_WAY);
		//$router[] = new Route('<presenter>/<action>', 'Homepage:default');                
		
                $router[] = $frontRouter = new RouteList('Front');
                $router[] = new Route('[<lang sk|cs|en>/]<presenter>/<action>/[<id>]', "Homepage:default");                                
                
                $router[] = $adminRouter = new RouteList('Admin');
                $router[] = new Route('[<lang sk|cs|en>/]admin/<presenter>/<action>/[<id>]', "Homepage:default");
                
                return $router;
	}

**My RestPresenter:**

namespace App\Presenters;

use Nette;

class RestPresenter extends Nette\Application\UI\Presenter
{      
    public function actionCreate() {
        $this->sendJson(['Action' => 'Create']);
    }

    public function actionRead() {        
        $this->sendJson(['Action' => 'Read']);
    }
    
    public function actionDelete() {
        $this->sendJson(['Action' => 'Delete']);
    }
    
    public function actionUpdate() {
        $this->sendJson(['Action' => 'Update']);
    }
}

Where could be the problem why the ApiRoute isn't used? How could I make it work?

**Comment by f3l1x** [comment]
I think it's repaired. Test the latest version please.
