### ISSUE TITLE
Release v2.0.4

### ISSUE THREAD

**Issue by martenb** [contributte/api-router#27]
Please, is it possible to release new 2.0.4 version with this 75c3c8e6d31d7c6f3bc10f22437273ad41245ce4. 
doctrine/cache": "~1.6.0 is blocking me, to install another package, ... It is one commit after 2.0.3.. 
It looks like all three commits after 2.0.3 will be save...

![image](https://user-images.githubusercontent.com/13311472/94998019-50ec2100-05af-11eb-9f13-ea8b16f5e884.png)

Thanks

**Comment by paveljanda** [comment]
https://github.com/contributte/api-router/releases/tag/v2.1.1

**Comment by martenb** [comment]
Thanks!
