### ISSUE TITLE
Problem with the newest version of  Nette Routes: Nette\Application\Routers\RouteList::getIterator() is deprecated, use getRouters().

### ISSUE THREAD

**Issue by ZdenekKrcal** [contributte/api-router#30]
Hi, please could you solve that?
After updated Nette I got this message:

Nette\Application\Routers\RouteList::getIterator() is deprecated, use getRouters().

**Comment by mstefan21** [comment]
#33 PR created

**Comment by f3l1x** [comment]
Solved
