### ISSUE TITLE
More advanced demo project or documentation?

### ISSUE THREAD

**Issue by tprochazka** [contributte/api-router#32]
I'm migrating my project from the great library `Drahak\Restful` which fully fits my needs, but it sadly abandoned and I was not able to make it working with a lot of changes in Nette itself. So I'm looking for some replacement. I was thinking about https://contributte.org/apitte/, but it quite over complicated for me simple usage. Then I found this library which looks simple enough. I was able to make it work in a much shorter time than apitte.

I just don't understand why it using `doctrine/cache` instead of Nette cache.

But the problem is a lack of documentation or at least some more advanced examples of usage.
Especially all possibilities of @ApiRoute() annotation
Is there some open source project which using it?

I would also expect the possibility to take parameters from the method signature directly, like
`public function actionContent(int $daysBack = 180, string $mode = "SIMPLE") {`
Should automatically add query parameters with type check and default value.

**Comment by f3l1x** [comment]
We've revealed archived skeleton.

https://github.com/contributte/api-router-skeleton

There is a plan to work on it. Any sponsorship is welcomed, even one time thing.

**Comment by f3l1x** [comment]
Solved https://github.com/contributte/api-router/commit/766a2250d86608c60adbae6c07c05fc34b9353ed
