### ISSUE TITLE
Registering the extension is missing from the docs?

### ISSUE THREAD

**Issue by patrickkusebauch** [contributte/api-router#34]
I see there is a DI extension in the source files, however, there is no mention that you need to register an extension anywhere in the docs/the installation guide.

Is the extension necessary? And if so, shouldn't it be mentioned in the docs?

**Comment by f3l1x** [comment]
Solved https://github.com/contributte/api-router/commit/766a2250d86608c60adbae6c07c05fc34b9353ed
