### ISSUE TITLE
problem with nette/reflection on php 8.1

### ISSUE THREAD

**Issue by ZdenekKrcal** [contributte/api-router#49]
Hi,

there is big problem with php 8.1
this package depends on nette/reflection but it doesn't work for php 8.1

Return type of Nette\Reflection\ClassType::getConstructor() should either be compatible with ReflectionClass::getConstructor(): ?ReflectionMethod, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

**Comment by f3l1x** [comment]
Hi ✋ I will put fixed nette/reflection class to contributte/utils.

**Comment by f3l1x** [comment]
Solved https://github.com/contributte/api-router/commit/83a7dee6cd5865313f8bbc07af320a714b246a9c
