### ISSUE TITLE
Routy vo formáte `/cars[/<manufacturer [a-z ]{1,}>`

### ISSUE THREAD

**Issue by romanmatyus** [contributte/api-router#5]
Neprišiel som na spôsob ako zadefinovať regulárnym výrazom parameter v url aj s medzerou.
Routeru sa nedá nastaviť regulárny výraz podobný nette routeru - s rozsahom platných znakov.

Všetky `[]` sa [prevádzajú](http://ublaboo.paveljanda.com/api/api-router/source-class-Ublaboo.ApiRouter.ApiRoute.html#312) na `()`.

**Comment by paveljanda** [comment]
ApiRouteru se nedají definovat regulárem parametry takto v routě. Dají se pak definovat regulárem v parameters. A mezera tam momentálně asi nejde. Pravda, kouknu se na to.

**Comment by paveljanda** [comment]
Aha, už jsem to pochopil. Requirements definuješ jinde. (http://ublaboo.paveljanda.com/api-router/annotation-routing - koukni na ten parametr "requirement" v anotaci)

Pomohlo?
